version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MvrLv@2418
      POSTGRES_DB: examdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  exam-app:
    build: .
    container_name: exam_app_container
    ports:
      - "3000:3000"   # Frontend exposed port (static)
      - "5000:5000"   # Backend API port
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: MvrLv@2418
      DB_NAME: examdb
    depends_on:
      - postgres

volumes:
  pgdata:
