version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MvrLv@2418
      POSTGRES_DB: examdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  exam-app:
    build: .
    container_name: exam_app_container
    ports:
      - "5000:40000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: MvrLv@2418
      DB_NAME: examdb
      DATABASE_URL: postgres://postgres:MvrLv@2418@postgres:5432/examdb
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
